In [2]:
import numpy as np
import gym as gym
import random
import time
from IPython.display import clear_output

In [161]:
env = gym.make("FrozenLake-v1")

env = gym.make("FrozenLake-v1", map_name="4x4",render_mode='ansi')

In [134]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n
q_table = np.zeros((state_space_size , action_space_size))

In [135]:
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [170]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.001
exploration_decay_rate = 0.001 

In [171]:
rewards_all_episode = []

#Q-Learning algo

for episode in range(num_episodes):
    state = env.reset()[0]
    
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        
    
        #Exploration-explitation trade-off
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, truncated, info = env.step(action)
           
        #update Q-table for (s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        state = new_state
        rewards_current_episode += reward
        
        if done == True:
            break
    
    #Exploration rate decay
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    
    rewards_all_episode.append(rewards_current_episode)

#Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episode),num_episodes/1000)
count = 10000
print("***********Average reward per thousnad episodes***********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count+=1000
    
#Print updatetd Q table
print("\n\n**********Q-Tabele**********\n")
print(q_table)

***********Average reward per thousnad episodes***********

10000 :  0.05600000000000004
11000 :  0.20600000000000016
12000 :  0.3990000000000003
13000 :  0.6150000000000004
14000 :  0.6970000000000005
15000 :  0.6950000000000005
16000 :  0.7470000000000006
17000 :  0.7400000000000005
18000 :  0.7140000000000005
19000 :  0.7610000000000006


**********Q-Tabele**********

[[0.58411175 0.51590712 0.51205686 0.50681254]
 [0.29643925 0.44633576 0.35409105 0.54209909]
 [0.41755447 0.42164003 0.40254922 0.50494597]
 [0.32038179 0.33738511 0.30353874 0.48483692]
 [0.6054752  0.41153038 0.33938564 0.42467797]
 [0.         0.         0.         0.        ]
 [0.3428869  0.17185554 0.17338668 0.10731726]
 [0.         0.         0.         0.        ]
 [0.29572402 0.3833905  0.3531403  0.66597822]
 [0.53212891 0.72350646 0.45753883 0.38754528]
 [0.6844191  0.34706554 0.28480146 0.38783623]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.45972525 0.

In [157]:
# Watch our agent play Frozen Lake by playing the best action 
# from each state according to the Q-table

for episode in range(3):
    # initialize new episode params
    state = env.reset()[0]
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):        
        # Show current state of environment on screen
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        # Choose action with highest Q-value for current state       
        action = np.argmax(q_table[state,:])
        new_state, reward, done, truncated, info = env.step(action)
        
        # Take new action

        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                # Agent reached the goal and won episode
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                # Agent stepped in a hole and lost episode 
                print("****You fell through a hole!****")
                time.sleep(3)
            clear_output(wait=True)
            break

        # Set new state
        state=new_state

env.close()

****You reached the goal!****
